name: lightRepair
version: 1.0-SNAPSHOT
main: de.lightplugins.repair.master.Main
api-version: 1.18
depend: []
softdepend: [ItemsAdder, EcoItems]
loadbefore: []
commands:
  lrepair:
    description: "The main command for the plugin"
    aliases: [lr, lrep]